# Generated by Django 3.2.8 on 2021-11-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_imag_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imag',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
