# Generated by Django 3.2.8 on 2021-11-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211124_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imag',
            new_name='image',
        ),
    ]
